device: 'cuda'
amp: True
pin_memory: True
non_blocking: True
prefetch: False

checkpoint_load:
checkpoint_save:
log:
dataset_path: './data'
dataset: 'gtsrb'

batch_size: 256
num_workers: 4
model: 'preactresnet18'

random_seed: 0


